// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-rP9H2Y8VCC425roxAaiUZ0xwl9EuHqc',
    appId: '1:852172347291:web:6751d67c07dd0dbb59f33e',
    messagingSenderId: '852172347291',
    projectId: 'act12-ec260',
    authDomain: 'act12-ec260.firebaseapp.com',
    storageBucket: 'act12-ec260.firebasestorage.app',
    measurementId: 'G-DPPRBHJVCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfKU8gzCJHdsg_NqdGkZ8eWVoy8D4f3-4',
    appId: '1:852172347291:android:bfe2d9eb4e55116e59f33e',
    messagingSenderId: '852172347291',
    projectId: 'act12-ec260',
    storageBucket: 'act12-ec260.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8KpvpuIbOhJu0zwq5YEapY1e8gIhizdc',
    appId: '1:852172347291:ios:5e02f09dbd35a92859f33e',
    messagingSenderId: '852172347291',
    projectId: 'act12-ec260',
    storageBucket: 'act12-ec260.firebasestorage.app',
    iosBundleId: 'com.example.act12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8KpvpuIbOhJu0zwq5YEapY1e8gIhizdc',
    appId: '1:852172347291:ios:5e02f09dbd35a92859f33e',
    messagingSenderId: '852172347291',
    projectId: 'act12-ec260',
    storageBucket: 'act12-ec260.firebasestorage.app',
    iosBundleId: 'com.example.act12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-rP9H2Y8VCC425roxAaiUZ0xwl9EuHqc',
    appId: '1:852172347291:web:1c140c83b11c3d8c59f33e',
    messagingSenderId: '852172347291',
    projectId: 'act12-ec260',
    authDomain: 'act12-ec260.firebaseapp.com',
    storageBucket: 'act12-ec260.firebasestorage.app',
    measurementId: 'G-1K3XDTKJ9V',
  );
}
